[package]
name = "primitives"
version = "0.1.0"
authors = ["Alexey Karasev <karasev.alexey@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
derive_more = "0.14"
log = "0.4"

