[package]
name = "tata-core"
version = "0.1.0"
authors = ["Alexey Karasev <karasev.alexey@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
async-std = "1.5"
futures = "0.3"
libp2p = "0.18"
log = "0.4"

[build-dependencies]
bindgen = "0.54"
